FROM quay.io/keycloak/keycloak:latest

#COPY --chown=keycloak:keycloak themes/quick-theme.jar /opt/keycloak/providers/

#RUN echo "Verifying providers directory contents:" && ls -l /opt/keycloak/providers

WORKDIR /opt/keycloak
#rofl comms